---
abstract: "Format or print values from an array or hash in one or more sorted, vertical columns.\n"
author:
  - 'Alan K. Stebbens <aks@stebbens.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Array-PrintCols
provides:
  Array::PrintCols:
    file: lib/Array/PrintCols.pm
    version: 2.5
requires:
  Carp: 0
  File::ShareDir: 1.00
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 2.5
